### ISSUE TITLE
remove dependency on system installation of SDL2

### ISSUE THREAD

**Issue by UnGast** [UnGast/swift-cross-platform-gui-example#6]
It could be possible to put all the SDL2 source files in a Swift package and compile it with the Swift sources.

**Comment by wbehrens-on-gh** [comment]
Is there any update on this? I'm currently running an arch system with all the sdl2 packages installed and running swift build inside of [my project](https://gitlab.com/WilliamBehrens/amalgam)  I get the following output and errors, 
[error.log](https://github.com/UnGast/swift-gui/files/5922746/error.log)

**Comment by UnGast** [comment]
The error should be fixed. It had something to do with converting the key ids which sdl provides to the key ids the framework uses. SDL's key ids seem to have different types on different systems, probably because of the way C interop is implemented. Please pull from master and try again.
Right now, my framework is probably not the gui library that "actually works" you are looking for. I'm currently redesigning a lot of the internals. You could try again in one or two months.
